<h1 style="text-align: center;">NumPy Methods</h1>

### Contents

<details>
  <summary style="cursor: pointer;">Click Here</summary>
    
- [np.sort](#np.sort)
- [np.append](#np.append)
- [np.concatenate](#np.concatenate)
- [np.unique](#np.unique)
- [np.expand_dims](#np.expand_dims)
- [np.where](#np.where)
- [np.argmax](#np.argmax)
- [np.cumsum](#np.cumsum)
- [np.percentile](#np.percentile)
- [np.histogram](#np.histogram)
- [np.corrcoef](#np.corrcoef)
- [np.isin](#np.isin)
- [np.flip](#np.flip)
- [np.put](#np.put)
- [np.delete](#np.delete)
- [np.clip](#np.clip)
- [Set Functions](#Set-Functions)
  - np.union1d
  - np.intersect1d
  - np.setdiff1d
  - np.setxor1d
  - np.in1d

</details>

In [1]:
import numpy as np

### np.sort

In [2]:
arr1 = np.random.randint(1, 100, 15)
arr2 = np.random.randint(1, 100, 24).reshape(6, 4)

print(f"Array 01: {arr1}")
print(f"Array 02:\n{arr2}")

Array 01: [62 32  7 38 66 67 81 17 58 98 98 69  4 65 42]
Array 02:
[[46 24 85 56]
 [13 96 46 99]
 [74  7 84 64]
 [30 68 85 84]
 [89 26 86 85]
 [ 9 54 66 54]]


In [3]:
x1 = np.sort(arr1)
x2 = np.sort(arr1)[::-1]

print(f"Sorted Array: {x1}")
print(f"Reverse Sorted: {x2}")

Sorted Array: [ 4  7 17 32 38 42 58 62 65 66 67 69 81 98 98]
Reverse Sorted: [98 98 81 69 67 66 65 62 58 42 38 32 17  7  4]


In [4]:
x1 = np.sort(arr2, axis=0)
x2 = np.sort(arr2, axis=1)

print(f"Column Sorted:\n{x1}")
print(f"\nRow Sorted:\n{x2}")

Column Sorted:
[[ 9  7 46 54]
 [13 24 66 56]
 [30 26 84 64]
 [46 54 85 84]
 [74 68 85 85]
 [89 96 86 99]]

Row Sorted:
[[24 46 56 85]
 [13 46 96 99]
 [ 7 64 74 84]
 [30 68 84 85]
 [26 85 86 89]
 [ 9 54 54 66]]


### np.append

In [5]:
print(f"1D Array:\n{arr1}")
print(f"Append 111 to 1D:\n{np.append(arr1, 111)}")

1D Array:
[62 32  7 38 66 67 81 17 58 98 98 69  4 65 42]
Append 111 to 1D:
[ 62  32   7  38  66  67  81  17  58  98  98  69   4  65  42 111]


In [6]:
# axis=0 is column and axis=1 is row
print(f"Appending 1 at each last row")
np.append(
    arr2, np.ones(
        (arr2.shape[0], 1)
    ), axis=1
)

Appending 1 at each last row


array([[46., 24., 85., 56.,  1.],
       [13., 96., 46., 99.,  1.],
       [74.,  7., 84., 64.,  1.],
       [30., 68., 85., 84.,  1.],
       [89., 26., 86., 85.,  1.],
       [ 9., 54., 66., 54.,  1.]])

### np.concatenate

In [7]:
arr3 = np.arange(6).reshape(2, 3)
arr4 = np.arange(6, 12).reshape(2, 3)

print(f"Array 01:\n{arr3}")
print(f"\nArray 02:\n{arr4}")

Array 01:
[[0 1 2]
 [3 4 5]]

Array 02:
[[ 6  7  8]
 [ 9 10 11]]


In [8]:
np.concatenate((arr3, arr4), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
np.concatenate((arr3, arr4), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

In [10]:
x1 = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])
np.unique(x1)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

In [11]:
print(f"Shape: {arr1.shape}")
print(f"Array: {arr1}\n")

x1 = np.expand_dims(arr1, axis=0)
print(f"Shape after expand_dim at axis=0: {x1.shape}")
print(f"Array after expand_dim at axis=0: {x1}\n")

x2 = np.expand_dims(arr1, axis=1)
print(f"Shape after expand_dim at axis=1: {x2.shape}")
print(f"Array after expand_dim at axis=1:\n{x2}")

Shape: (15,)
Array: [62 32  7 38 66 67 81 17 58 98 98 69  4 65 42]

Shape after expand_dim at axis=0: (1, 15)
Array after expand_dim at axis=0: [[62 32  7 38 66 67 81 17 58 98 98 69  4 65 42]]

Shape after expand_dim at axis=1: (15, 1)
Array after expand_dim at axis=1:
[[62]
 [32]
 [ 7]
 [38]
 [66]
 [67]
 [81]
 [17]
 [58]
 [98]
 [98]
 [69]
 [ 4]
 [65]
 [42]]


### np.where

In [12]:
print(f"Array: {arr1}")

x1 = np.where(arr1>50)
print(f"Indicies of Array>50: {x1}")

# replace all the elements >50 with 0
# np.where(condition, true, false)
x2 = np.where(arr1>50, 0, arr1)
print(f"Replace element>50 with 0: {x2}")

# replace all the elements <50 with zero
x3 = np.where(arr1>50, arr1, 0)
print(f"Replace element<50 with 0: {x3}")

# replace all the even numbers with zero
x4 = np.where(arr1%2==0, 0, arr1)
print(f"Replace even elements with 0: {x4}")

Array: [62 32  7 38 66 67 81 17 58 98 98 69  4 65 42]
Indicies of Array>50: (array([ 0,  4,  5,  6,  8,  9, 10, 11, 13], dtype=int64),)
Replace element>50 with 0: [ 0 32  7 38  0  0  0 17  0  0  0  0  4  0 42]
Replace element<50 with 0: [62  0  0  0 66 67 81  0 58 98 98 69  0 65  0]
Replace even elements with 0: [ 0  0  7  0  0 67 81 17  0  0  0 69  0 65  0]


### np.argmax

In [13]:
print(f"Array: {arr1}")

x1 = np.argmax(arr1)
x2 = np.argmin(arr1)

print(f"Max Element Index: {x1}")
print(f"Min Element Index: {x2}")

print(f"\nArray:\n{arr2}\n")

x3 = np.argmax(arr2, axis=0)
x4 = np.argmax(arr2, axis=1)

print(f"Max Element Index: {x3}")
print(f"Max Element Index: {x4}")

Array: [62 32  7 38 66 67 81 17 58 98 98 69  4 65 42]
Max Element Index: 9
Min Element Index: 12

Array:
[[46 24 85 56]
 [13 96 46 99]
 [74  7 84 64]
 [30 68 85 84]
 [89 26 86 85]
 [ 9 54 66 54]]

Max Element Index: [4 1 4 1]
Max Element Index: [2 3 2 2 0 2]


### np.cumsum

In [14]:
arr = np.array([1, 2, 3, 4, 5])

x1 = np.cumsum(arr)
x2 = np.cumprod(arr)

print(f"Array: {arr}")
print(f"Cumulative Sum: {x1}")
print(f"Cumulative Product: {x2}")

Array: [1 2 3 4 5]
Cumulative Sum: [ 1  3  6 10 15]
Cumulative Product: [  1   2   6  24 120]


In [15]:
print(f"Array:\n{arr2}")

x1 = np.cumsum(arr2, axis=0)
x2 = np.cumsum(arr2, axis=1)

print(f"\nCumulative Sum Axis=0 (Col):\n{x1}")
print(f"\nCumulative Sum Axis=1 (Row):\n{x2}")

Array:
[[46 24 85 56]
 [13 96 46 99]
 [74  7 84 64]
 [30 68 85 84]
 [89 26 86 85]
 [ 9 54 66 54]]

Cumulative Sum Axis=0 (Col):
[[ 46  24  85  56]
 [ 59 120 131 155]
 [133 127 215 219]
 [163 195 300 303]
 [252 221 386 388]
 [261 275 452 442]]

Cumulative Sum Axis=1 (Row):
[[ 46  70 155 211]
 [ 13 109 155 254]
 [ 74  81 165 229]
 [ 30  98 183 267]
 [ 89 115 201 286]
 [  9  63 129 183]]


### np.percentile

In [16]:
# Percentile(x) = (Number of values fall under ‘x’/total number of values) × 100
# P = (n/N) × 100

x1 = np.percentile(arr1, 0)
x2 = np.percentile(arr1, 25)
x3 = np.percentile(arr1, 50)
x4 = np.percentile(arr1, 75)
x5 = np.percentile(arr1, 100)

print(f"Array: {arr1}\n")
print(f"0 Percentile (Min): {x1}")
print(f"25 Percentile: {x2}")
print(f"50 Percentile (Median): {x3}")
print(f"75 Percentile: {x4}")
print(f"100 Percentile (Max): {x5}")

Array: [62 32  7 38 66 67 81 17 58 98 98 69  4 65 42]

0 Percentile (Min): 4.0
25 Percentile: 35.0
50 Percentile (Median): 62.0
75 Percentile: 68.0
100 Percentile (Max): 98.0


### np.histogram

In [17]:
print(f"Array: {arr1}")

np.histogram(arr1, bins=[0, 20, 40, 60, 80, 100])

Array: [62 32  7 38 66 67 81 17 58 98 98 69  4 65 42]


(array([3, 2, 2, 5, 3], dtype=int64), array([  0,  20,  40,  60,  80, 100]))

### np.corrcoef

In [18]:
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

x1 = np.corrcoef(salary, experience)

print(f"Correlation Table:\n{x1}\n")
print(f"Correlation Value: {x1[0, 1]}")

Correlation Table:
[[1.         0.25344572]
 [0.25344572 1.        ]]

Correlation Value: 0.25344572266626864


### np.isin

In [19]:
items = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
x1 = np.isin(arr1, items)

print(f"Array: {arr1}")
print(f"Boolean:\n{x1}")
print(f"Found Element: {arr1[x1]}")

Array: [62 32  7 38 66 67 81 17 58 98 98 69  4 65 42]
Boolean:
[False False  True False False False False False False False False False
  True False False]
Found Element: [7 4]


### np.flip

In [20]:
x1 = np.flip(arr1)

print(f"Array: {arr1}")
print(f"Flip: {x1}")

Array: [62 32  7 38 66 67 81 17 58 98 98 69  4 65 42]
Flip: [42 65  4 69 98 98 58 17 81 67 66 38  7 32 62]


In [21]:
x1 = np.flip(arr2, axis=0)
x2 = np.flip(arr2, axis=1)

print(f"Array:\n{arr2}\n")
print(f"Fliped at axis=0:\n{x1}\n")
print(f"Fliped at axis=1:\n{x2}")

Array:
[[46 24 85 56]
 [13 96 46 99]
 [74  7 84 64]
 [30 68 85 84]
 [89 26 86 85]
 [ 9 54 66 54]]

Fliped at axis=0:
[[ 9 54 66 54]
 [89 26 86 85]
 [30 68 85 84]
 [74  7 84 64]
 [13 96 46 99]
 [46 24 85 56]]

Fliped at axis=1:
[[56 85 24 46]
 [99 46 96 13]
 [64 84  7 74]
 [84 85 68 30]
 [85 86 26 89]
 [54 66 54  9]]


### np.put

In [22]:
print(f"Array: {arr1}")
np.put(arr1, [0, 1], [111, 222])
print(f"Updated: {arr1}")

Array: [62 32  7 38 66 67 81 17 58 98 98 69  4 65 42]
Updated: [111 222   7  38  66  67  81  17  58  98  98  69   4  65  42]


### np.delete

In [23]:
x1 = np.delete(arr1, [0, 1])

print(f"Array: {arr1}")
print(f"After Deletion: {x1}")

Array: [111 222   7  38  66  67  81  17  58  98  98  69   4  65  42]
After Deletion: [ 7 38 66 67 81 17 58 98 98 69  4 65 42]


### np.clip

In [24]:
print(f"Array: {arr1}")

np.clip(arr1, a_min=25, a_max=75)

Array: [111 222   7  38  66  67  81  17  58  98  98  69   4  65  42]


array([75, 75, 25, 38, 66, 67, 75, 25, 58, 75, 75, 69, 25, 65, 42])

### Set Functions

In [25]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([3, 4, 5, 6, 7])

print(f"Union: {np.union1d(x1, x2)}")
print(f"Intersection: {np.intersect1d(x1, x2)}")
print(f"Unique is x1: {np.setdiff1d(x1, x2)}")
print(f"Unique in x2: {np.setdiff1d(x2, x1)}")
print(f"Unique in both: {np.setxor1d(x1, x2)}")
print(f"Search 1 in x1: {np.in1d(x1, 1)}")
print(f"Return Search Element: {x1[np.in1d(x1, 1)]}")

Union: [1 2 3 4 5 6 7]
Intersection: [3 4 5]
Unique is x1: [1 2]
Unique in x2: [6 7]
Unique in both: [1 2 6 7]
Search 1 in x1: [ True False False False False]
Return Search Element: [1]
