<h1 style="text-align: center;">NumPy Advanced</h1>

### Contents

- [Boolean Indexing](#Boolean-Indexing)
- [Broadcasting](#Broadcasting)

In [1]:
import numpy as np

### Boolean Indexing

In [2]:
arr = np.random.randint(1, 100, 24).reshape(6, 4)
arr

array([[ 6, 71, 95, 58],
       [76, 57, 47, 19],
       [20, 20, 29, 95],
       [92, 79, 48, 10],
       [49, 88, 53, 27],
       [39, 53, 87, 94]])

In [3]:
arr>50

array([[False,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False,  True],
       [ True,  True, False, False],
       [False,  True,  True, False],
       [False,  True,  True,  True]])

In [4]:
# numbers greater than 50

condition = arr>50
arr[condition]

array([71, 95, 58, 76, 57, 95, 92, 79, 88, 53, 53, 87, 94])

In [5]:
# numbers greater than 50 and are even

condition = (arr>50) & (arr%2==0)
arr[condition]

array([58, 76, 92, 88, 94])

In [6]:
# numbers not divisible by 7

condition = ~(arr%7==0)
arr[condition]

array([ 6, 71, 95, 58, 76, 57, 47, 19, 20, 20, 29, 95, 92, 79, 48, 10, 88,
       53, 27, 39, 53, 87, 94])

### Broadcasting

- The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. 
- The smaller array is “broadcast” across the larger array so that they have compatible shapes.

#### Rules   

1. Make the two arrays have the same number of dimensions.      
2. Make each dimension of the two arrays the same size.         

#### Steps       

- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.     
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.       
  arr1 = (3, 4)          
  arr2 = (4) -> (1, 4) -> (3, 4)


#### Note     

- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.         

<div style="text-align:center;">
    <img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" alt="Broadcasting">
</div>

In [7]:
arr1 = np.arange(12).reshape(4, 3)
arr2 = np.arange(3)

print(f"array 01:\n{arr1}\n")
print(f"array 02:\n{arr2}\n")

print(f"Addition (Broadcasting):\n{arr1+arr2}")

array 01:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

array 02:
[0 1 2]

Addition (Broadcasting):
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [8]:
# broadcasting: stretched 1 to required amount 3 on both arrays
arr1 = np.arange(3).reshape(1, 3)
arr2 = np.arange(3).reshape(3, 1)

print(f"array 01:\n{arr1}\n")
print(f"array 02:\n{arr2}\n")

print(f"Addition (Broadcasting):\n{arr1+arr2}")

array 01:
[[0 1 2]]

array 02:
[[0]
 [1]
 [2]]

Addition (Broadcasting):
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [9]:
arr1 = np.arange(3).reshape(1, 3)
arr2 = np.arange(4).reshape(4, 1)

print(f"array 01:\n{arr1}\n")
print(f"array 02:\n{arr2}\n")

print(f"Addition (Broadcasting):\n{arr1+arr2}")

array 01:
[[0 1 2]]

array 02:
[[0]
 [1]
 [2]
 [3]]

Addition (Broadcasting):
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [10]:
# shape -> (1,1)
arr1 = np.array([1])

# shape -> (2,2)
arr2 = np.arange(4).reshape(2,2)

print(f"array 01:\n{arr1}\n")
print(f"array 02:\n{arr2}\n")

print(f"Addition (Broadcasting):\n{arr1+arr2}")

array 01:
[1]

array 02:
[[0 1]
 [2 3]]

Addition (Broadcasting):
[[1 2]
 [3 4]]


In [11]:
try:
    arr1 = np.arange(12).reshape(3, 4)
    arr2 = np.arange(12).reshape(4, 3)

    print(f"Addition:\n{arr1+arr2}")
except:
    print("Broadcasting not possible.")

Broadcasting not possible.


In [12]:
try:
    arr1 = np.arange(16).reshape(4,4)
    arr2 = np.arange(4).reshape(2,2)

    print(f"Addition:\n{arr1+arr2}")
except:
    print("Broadcasting not possible.")

Broadcasting not possible.
